mybatis:
  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.bighouse.pojo
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://39.107.243.241:3306/big_house?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    url: jdbc:mysql://192.168.0.17:3306/big_house?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: P@s5word
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 28740000
      pool-name: DatebookHikariCP
      connection-test-query: SELECT 1

  redis:
    database: 0                   # Redis数据库索引（默认为0）
    host: 39.107.243.241          # Redis服务器地址
    port: 6379                    # Redis服务器连接端口
    # password: 123456              # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 10            # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1              # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8               # 连接池中的最大空闲连接
        min-idle: 0               # 连接池中的最小空闲连接
    timeout: 1000                 # 连接超时时间（毫秒）

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
    - 39.107.243.241:22122
#    - 192.168.1.106:22122